/*
 ************************************************************************************************************
 |  NOMBRE                 : CTR_UR_ErrorAcceso					   										    |
 |  TIPO                   : APEX CLASS																		|
 |  REQUERIMIENTO          : MEJORAS UR                                                                  	|
 |  DESCRIPCION            :                                                                                |  														
 ************************************************************************************************************
 |  VERSIÓN    *    FECHA C/M    *    RESPONSABLE    *    OBSERVACIONES										|
 |    1.0      *    2019/08/01   *    JUAN ESPINOZA  *    Creación Clase									|
 |     																										|
 ************************************************************************************************************
*/ 

public  class CTR_UR_ErrorAcceso {
    public void Inicio() {

    }
}