@isTest
public class EscritorioDigitalError_Controller_Test {
 	@isTest static void LoadAlerta_01() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-1';
        Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    
    @isTest static void LoadAlerta_02() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-2';
        Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_03() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-3';
        Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_04() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-4';
        Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_05() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-5';
        Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_06() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-6';
        Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
     @isTest static void LoadAlerta_07() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'REQUERIMIENTO|-7';
         Con.Excepcion = 'Excepcion';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
 
    @isTest static void LoadAlerta_08() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'PERSISTENCIA|-5';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_09() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'PERSISTENCIA|-4';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_10() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'PERSISTENCIA|-3';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_11() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'PERSISTENCIA|-2';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_12() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'PERSISTENCIA|-1';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_13() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'PERSISTENCIA|0';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_14() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'DERIVARCASO|-3';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_15() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'DERIVARCASO|1';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
     @isTest static void LoadAlerta_16() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'DERIVARCASO|3';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
     @isTest static void LoadAlerta_17() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'DERIVARCASO|4';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_18() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'CAMBIOESTADO|-1';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_19() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'CAMBIOESTADO|2';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_20() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'CAMBIOESTADO|3';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_21() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'COMUNICATION';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
     @isTest static void LoadAlerta_22() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'OTHER';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    
    @isTest static void LoadAlerta_23() {
        Test.startTest();
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();
        Con.Operacion = 'DERIVARCASO|6';
        Con.LoadAlerta();       
        Test.StopTest();
    } 
    @istest static void constructor_a() {
        Test.StartTest();       
        Factory.crearAccountAnonimo();         
        Account cuenta = Factory.cuenta.buildInsert();                
        Case caso = FactoryEscritorio.buildCaso('Solicitudes', cuenta);     
        caso.Tipo_de_Requerimiento__c = 'Solicitudes';        
        caso.Detalle_Solicitud__c = 'ED - Solicitud garantía estatal';
        caso.Id_Requerimiento_EscritorioDigital__c = '36';        
        ApexPages.StandardController stdHR = new ApexPages.StandardController(caso);            
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller(stdHR);      
        Test.StopTest();
    }
    
    @istest static void constructor_b() {
        Test.StartTest();       
        Factory.crearAccountAnonimo();         
        Account cuenta = Factory.cuenta.buildInsert();                
        Case caso = FactoryEscritorio.buildCaso('Solicitudes', cuenta);     
        caso.Tipo_de_Requerimiento__c = 'Solicitudes';        
        caso.Detalle_Solicitud__c = 'ED - Solicitud garantía estatal';
        caso.Id_Requerimiento_EscritorioDigital__c = '36';        
        caso.CASO_Poliza_Asoc__c = '12345';
        ApexPages.StandardController stdHR = new ApexPages.StandardController(caso);            
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller(stdHR);      
        Test.StopTest();
    }
    
     @isTest static void ToCase() {
        Test.startTest();
        Factory.crearAccountAnonimo();         
        Account cuenta = Factory.cuenta.buildInsert();                
        EscritorioDigitalError_Controller Con = new EscritorioDigitalError_Controller();    
        Con.Caso = FactoryEscritorio.buildCaso('Solicitudes', cuenta);         
        Con.ToCase();
        Test.stopTest();
    } 
}