@isTest
public class EscritorioDigitalTest {    
	
     @isTest static void obtenerRequerimiento1() {
        String Tipo = 'RRVVTIPO0001';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Pensión Sobrevivencia');	
	}
    
    @isTest static void obtenerRequerimiento2() {
        String Tipo = 'RRVVTIPO0002';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Pensión Sobrevivencia');	
	}
    
     @isTest static void obtenerRequerimiento3() {
        String Tipo = 'RRVVTIPO0003';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Pensión Sobrevivencia');	
	}
    
     @isTest static void obtenerRequerimiento4() {
        String Tipo = 'RRVVTIPO0004';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Pensión Sobrevivencia');	
	}
    
     @isTest static void obtenerRequerimiento5() {
        String Tipo = 'RRVVTIPO0005';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Cuota Mortuoria');	
	}
    
    @isTest static void obtenerRequerimiento6() {
        String Tipo = 'RRVVTIPO0006';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Mantención forma de pago');	
	}
    /*
     @isTest static void obtenerRequerimiento7() {
        String Tipo = 'RRVVTIPO0007';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Mantención poder de cobro a tercero');	
	}*/
    
     @isTest static void obtenerRequerimiento8() {
        String Tipo = 'RRVVTIPO0008';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Declaracion Beneficiarios Periodo Garantizado');	
	}  
    /* 
     @isTest static void obtenerRequerimiento10() {
        String Tipo = 'RRVVTIPO0010';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Asignacion Familiar');	
	}
    
     @isTest static void obtenerRequerimiento11() {
        String Tipo = 'RRVVTIPO0011';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Asignacion Familiar');	
	}
    
     @isTest static void obtenerRequerimiento12() {
        String Tipo = 'RRVVTIPO0012';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Asignacion Familiar');	
	}
    */
     @isTest static void obtenerRequerimiento13() {
        String Tipo = 'RRVVTIPO0013';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Asignacion Familiar');	
	}
    /*
     @isTest static void obtenerRequerimiento14() {
        String Tipo = 'RRVVTIPO0014';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Asignacion Familiar');	
	}
    
     @isTest static void obtenerRequerimiento15() {
        String Tipo = 'RRVVTIPO0015';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Declaración Ingresos nuevos beneficiarios');	
	}
    */
     @isTest static void obtenerRequerimiento16() {
        String Tipo = 'RRVVTIPO0016';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Declaración Ingresos Actualización');	
	}
    
     @isTest static void obtenerRequerimiento17() {
        String Tipo = 'RRVVTIPO0017';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud de Extinción');	
	}
    
    @isTest static void obtenerRequerimiento18() {
        String Tipo = 'RRVVTIPO0018';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud de Extinción');	
	}
    
    @isTest static void obtenerRequerimiento19() {
        String Tipo = 'RRVVTIPO0019';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud de Extinción');	
	}
    
    @isTest static void obtenerRequerimiento20() {
        String Tipo = 'RRVVTIPO0020';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud de Extinción');	
	}
    
    @isTest static void obtenerRequerimiento21() {
        String Tipo = 'RRVVTIPO0021';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud de Extinción');	
	}
    
     @isTest static void obtenerRequerimiento22() {
        String Tipo = 'RRVVTIPO0022';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Garantía Estatal');	
	}
    
     @isTest static void obtenerRequerimiento23() {
        String Tipo = 'RRVVTIPO0023';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Garantía Estatal');	
	}
    
     @isTest static void obtenerRequerimiento24() {
        String Tipo = 'RRVVTIPO0024';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Garantía Estatal');	
	}
    
     @isTest static void obtenerRequerimiento25() {
        String Tipo = 'RRVVTIPO0025';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Garantía Estatal');	
	}
    
     @isTest static void obtenerRequerimiento26() {
        String Tipo = 'RRVVTIPO0026';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Solicitud Garantía Estatal');	
	}
    
     @isTest static void obtenerRequerimiento27() {
        String Tipo = 'RRVVTIPO0027';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == 'Renuncia Garantía Estatal');	
	}
    
    @isTest static void obtenerRequerimiento() {
        String Tipo = 'RRVVTIPO0033';
        String Requerimiento = EscritorioDigital.Requerimiento(Tipo);
        
        System.assert(Requerimiento == '');	
	}
    
     @isTest static void obtenerSolicitante1() {
    	String Tipo = 'RRVVTIPO0001';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Cónyuge');	
	}
    
     @isTest static void obtenerSolicitante2() {
    	String Tipo = 'RRVVTIPO0002';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Madre Filiación N/M');	
	}
   
    @isTest static void obtenerSolicitante3() {
    	String Tipo = 'RRVVTIPO0003';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo menor de 18 años');	
	}
    
    @isTest static void obtenerSolicitante4() {
    	String Tipo = 'RRVVTIPO0004';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo mayor de 18 años');	
	}
    
     @isTest static void obtenerSolicitante5() {
    	String Tipo = 'RRVVTIPO0005';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Persona o Entidad que realiza el gasto');	
	}
    
    @isTest static void obtenerSolicitante6() {
    	String Tipo = 'RRVVTIPO0006';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Rentista Titular');	
	}
    /*
    @isTest static void obtenerSolicitante7() {
    	String Tipo = 'RRVVTIPO0007';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Rentista Titular');	
	}
    */
     @isTest static void obtenerSolicitante8() {
    	String Tipo = 'RRVVTIPO0008';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Rentista Titular');	
	}
    /*
    @isTest static void obtenerSolicitante10() {
    	String Tipo = 'RRVVTIPO0010';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Cónyuge');	
	}
    
    @isTest static void obtenerSolicitante11() {
    	String Tipo = 'RRVVTIPO0011';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo menor de 18 años');	
	}
    
    @isTest static void obtenerSolicitante12() {
    	String Tipo = 'RRVVTIPO0012';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo mayor de 18 años');	
	}*/
    
    @isTest static void obtenerSolicitante13() {
    	String Tipo = 'RRVVTIPO0013';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Afiliado Titular');	
	}
    /*
    @isTest static void obtenerSolicitante14() {
    	String Tipo = 'RRVVTIPO0014';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Madre o Padre (Ascendente)');	
	}
        
    @isTest static void obtenerSolicitante15() {
    	String Tipo = 'RRVVTIPO0015';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Afiliado Titular');	
	}
    */
     @isTest static void obtenerSolicitante16() {
    	String Tipo = 'RRVVTIPO0016';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Afiliado Titular');	
	}
    
    @isTest static void obtenerSolicitante17() {
    	String Tipo = 'RRVVTIPO0017';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Cónyuge');	
	}
    
     @isTest static void obtenerSolicitante18() {
    	String Tipo = 'RRVVTIPO0018';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo menor de 18 años');	
	}
    
     @isTest static void obtenerSolicitante19() {
    	String Tipo = 'RRVVTIPO0019';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo mayor de 18 años');	
	}
    
    @isTest static void obtenerSolicitante20() {
    	String Tipo = 'RRVVTIPO0020';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Otros');	
	}
    
    @isTest static void obtenerSolicitante21() {
    	String Tipo = 'RRVVTIPO0021';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Madre o Padre (Ascendente)');	
	}
    
     @isTest static void obtenerSolicitante22() {
    	String Tipo = 'RRVVTIPO0022';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Afiliado Titular');	
	}
    
    @isTest static void obtenerSolicitante23() {
    	String Tipo = 'RRVVTIPO0023';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Cónyuge');	
	}
    
     @isTest static void obtenerSolicitante24() {
    	String Tipo = 'RRVVTIPO0024';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Madre Filiación N/M');	
	}
    
     @isTest static void obtenerSolicitante25() {
    	String Tipo = 'RRVVTIPO0025';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo menor de 18 años');	
	}
    
     @isTest static void obtenerSolicitante26() {
    	String Tipo = 'RRVVTIPO0026';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Hijo mayor de 18 años');	
	}
    
     @isTest static void obtenerSolicitante27() {
    	String Tipo = 'RRVVTIPO0027';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == 'Afiliado Titular');	
	}
    
   
    @isTest static void obtenerSolicitante() {
    	String Tipo = 'RRVVTIPO0033';
   		
        String Solicitante = EscritorioDigital.Solicitante(Tipo);
        
        System.assert(Solicitante == '');	
	}
    
    @isTest static void obtenerFormulario1() {
    	String DetalleSolicitud = 'Solicitud pensión sobrevivencia';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Solicitud Pensión Sobrevivencia');	
	}
    
    @isTest static void obtenerFormulario2() {
    	String DetalleSolicitud = 'Solicitud cuota mortuoria';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Cuota Mortuoria');	
	}
    
    @isTest static void obtenerFormulario3() {
    	String DetalleSolicitud = 'Solicitud cambio pago pensión';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Mantención forma de pago');	
	}
    /*
   @isTest static void obtenerFormulario4() {
    	String DetalleSolicitud = 'Solicitud de ingreso poder notarial';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Mantención poder de cobro a tercero');	
	}
    */
   @isTest static void obtenerFormulario5() {
    	String DetalleSolicitud = 'Solicitud periodo garantizado';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Declaracion Beneficiarios Periodo Garantizado');	
	}
    
    @isTest static void obtenerFormulario6() {
    	String DetalleSolicitud = 'Solicitud de incorporación/ Renovación asignación familiar';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Solicitud Asignacion Familiar');	
	}
        
    @isTest static void obtenerFormulario7() {
    	String DetalleSolicitud = 'Solicitud garantía estatal';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Solicitud Garantía Estatal');	
	}
    
	@isTest static void obtenerFormulario8() {
    	String DetalleSolicitud = 'Solicitud de Extinción';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Solicitud de Extinción');	
	}
    
 /*   @isTest static void obtenerFormulario9() {
    	String DetalleSolicitud = 'Declaración Ingresos nuevos beneficiarios';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Declaración Ingresos nuevos beneficiarios');	
	}*/
    /*
     @isTest static void obtenerFormulario10() {
    	String DetalleSolicitud = 'Declaración Ingresos Actualización';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Declaración Ingresos Actualización');	
	}
    */
     @isTest static void obtenerFormulario11() {
    	String DetalleSolicitud = 'Renuncia Garantía Estatal';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Renuncia Garantía Estatal');	
	}
    
     @isTest static void obtenerFormulario12() {
    	String DetalleSolicitud = 'Declaración Ingresos Actualización';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == 'Renovación de Asignación Familiar');	
	}
    
	@isTest static void obtenerFormulario() {
    	String DetalleSolicitud = 'Renuncia Garantía Estatals';
   		
        String Formulario = EscritorioDigital.Formulario(DetalleSolicitud);
        
        System.assert(Formulario == '');	
	}   
    
    @isTest static void ValidaSolicitud1() {
    	String DetalleSolicitud = 'Solicitud cuota mortuoria';
   		
        boolean Valida =  EscritorioDigital.ValidaSolicitud(DetalleSolicitud);
        
        System.assert(Valida == true);	
	}
    
     @isTest static void ValidaSolicitud2() {
    	String DetalleSolicitud = 'Solicitud cuota mortuorias';
   		
        boolean Valida =  EscritorioDigital.ValidaSolicitud(DetalleSolicitud);
        
        System.assert(Valida == false);	
	}
}