/**
* Globant
* @author           Javier Tibamoza
* @email: 			javier.armando@globant.com
* Project:          Integraciones con GCP
* Description:      Clase base para la clase de prueba de la clase TriggerHandlerBase
* Changes (Version)
* -------------------------------------
*            No.    Date           Author                           Description      
*            ----   ----------     ---------------------------     -------------    
* @version   1.0    13/07/2021     Javier Tibamoza JATC 	       Class Created
***********************************************************************************************************************/
public class TestTriggerHandlerBase extends TriggerHandlerBase{
    
    public TestTriggerHandlerBase() {
    
    }

    public override void mainEntry(TriggerParameters tp){

    }
}